server:
  port: 9999

jdbc:
  driver: com.mysql.jdbc.Driver
  url: jdbc:mysql://127.0.0.1:3306/spring_test?useSSL=false&characterEncoding=utf8
  username: root
  password: 654321


mybatis-plus:
  # 自定义mapper.xml的路径
  mapper-locations: classpath*:/mapper/*Mapper.xml